sudo: false
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
  - "9"
install:
  - npm install
script: npm test
before_deploy: npm run build
deploy:
  provider: npm
  email: joamag@gmail.com
  skip_cleanup: true
  api_key:
    secure: PQbR6p6bj/ghCIXFrVnDB1VrO7sgZU5RF3MKGaNJiRqsbESzQjA6LQ4mHzT9T8O9JgTIH5BGLgqK0+n1/l0wM2Fn8C7rICh1WsLZ+RT1vpHH/5kWRJzpPQ+BeLrlZ1tLSVC7ExA+xCo3d7TE8YC3oHK4dtCe9ShrShWGOffYREQy+GhJ9qP4kcIvvdabongB7TPklPACAMYaivX/BjxPK6nzRhGvkqdTlV3cbT9iAFHftVGAfs1foAobXyZ+paY14/fSEHYYkbcb5r9CtDLD+xz0d0wjfwCQhqs5R4kCWjgJPTO2LLDFzG9GOr1B6ZF7O+hTYk8XNkDciq8OM6h9r/JQ3IJl2ayR6XbKc0pPGsjYhGSJm5vCvmx3UdifXIufJ1uYaaxW7Js4y6nUPKo7l0GAt60WGsIi7cWCtXkO3B2sxlIiYvR3PU3J7ZnRIrA4J+Ttokdfs1Ezcotj/VGRuAd9TUZcMABpfllwI/V5+VNUCWaT3+sYoNX62Hqa+l5h3wEEXd6QXWRb9GDQis1chPCtKwebCtHm26SrFNLyeaJG6v7rmgzAX+bTLhXKI6HT7wnNVwZUrUW+iirE2dUYdHNgJbgC/BrPDqa8zpRzXCHxk2sA1KnNJhLyUaJqTAorhKL4DYVRJESX2nXYAPT7M3d7oy+wnmYoCNPnFIYZruA=
  on:
    tags: true
    node_js: "7"
