name: Main Workflow
on: [push]
jobs:
  build:
    name: Build
    strategy:
      matrix:
        node-version: [7, 8, 9, 10]
    runs-on: ubuntu-latest
    container: node:${{ matrix.node-version }}
    steps:
      - uses: actions/checkout@v1
      - run: node --version
      - run: npm install
      - run: npm install --only=dev
      - run: npm run build
      - run: npm test
